name: PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  title:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: thehanimo/pr-title-checker@v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          local_configuration_path: .github/pr-title-checker-config.json
          pass_on_octokit_error: false
